// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLDvkFGm5PbbppHxoHp_SmRE1vALTf6IQ',
    appId: '1:1030361143944:web:e12a042f594ab756f09d3d',
    messagingSenderId: '1030361143944',
    projectId: 'civicpulse-ai',
    authDomain: 'civicpulse-ai.firebaseapp.com',
    storageBucket: 'civicpulse-ai.firebasestorage.app',
    measurementId: 'G-WX18SFBZV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhftVWJo5DH1iQixO4DRekSavz_pegPtw',
    appId: '1:1030361143944:android:49bd4738970f0b90f09d3d',
    messagingSenderId: '1030361143944',
    projectId: 'civicpulse-ai',
    storageBucket: 'civicpulse-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoG2Al91PFunxbH93HO5Bl32z9xD6YA-U',
    appId: '1:1030361143944:ios:b2783cc79a69cb37f09d3d',
    messagingSenderId: '1030361143944',
    projectId: 'civicpulse-ai',
    storageBucket: 'civicpulse-ai.firebasestorage.app',
    iosBundleId: 'com.qalb.qalb',
  );
}
